// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tasks.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNewTask = `-- name: CreateNewTask :exec
INSERT INTO
  tasks (
    workspace_id,
    assignee,
    created_by,
    name,
    description,
    due,
    parent_task,
    status,
    priority
  )
VALUES
($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateNewTaskParams struct {
	WorkspaceID uuid.UUID
	Assignee    uuid.NullUUID
	CreatedBy   uuid.NullUUID
	Name        string
	Description sql.NullString
	Due         sql.NullTime
	ParentTask  uuid.NullUUID
	Status      NullTaskStatus
	Priority    NullTaskPriority
}

func (q *Queries) CreateNewTask(ctx context.Context, arg CreateNewTaskParams) error {
	_, err := q.db.ExecContext(ctx, createNewTask,
		arg.WorkspaceID,
		arg.Assignee,
		arg.CreatedBy,
		arg.Name,
		arg.Description,
		arg.Due,
		arg.ParentTask,
		arg.Status,
		arg.Priority,
	)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getChildTasks = `-- name: GetChildTasks :many
SELECT id, workspace_id, assignee, created_by, name, description, due, parent_task, status, priority, created_at, updated_at FROM tasks
WHERE parent_task = $1
ORDER BY created_at DESC
OFFSET $2
LIMIT $3
`

type GetChildTasksParams struct {
	ParentTask uuid.NullUUID
	Offset     int32
	Limit      int32
}

func (q *Queries) GetChildTasks(ctx context.Context, arg GetChildTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getChildTasks, arg.ParentTask, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Assignee,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Due,
			&i.ParentTask,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, workspace_id, assignee, created_by, name, description, due, parent_task, status, priority, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskById(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Assignee,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.Due,
		&i.ParentTask,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceDueTasks = `-- name: GetWorkspaceDueTasks :many
SELECT id, workspace_id, assignee, created_by, name, description, due, parent_task, status, priority, created_at, updated_at FROM tasks
WHERE due > CURRENT_DATE
ORDER BY created_at DESC
OFFSET $1
LIMIT $2
`

type GetWorkspaceDueTasksParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetWorkspaceDueTasks(ctx context.Context, arg GetWorkspaceDueTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceDueTasks, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Assignee,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Due,
			&i.ParentTask,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceTasks = `-- name: GetWorkspaceTasks :many
SELECT id, workspace_id, assignee, created_by, name, description, due, parent_task, status, priority, created_at, updated_at FROM tasks
WHERE workspace_id = $1 AND status != 'completed'
ORDER BY created_at DESC
OFFSET $2
LIMIT $3
`

type GetWorkspaceTasksParams struct {
	WorkspaceID uuid.UUID
	Offset      int32
	Limit       int32
}

func (q *Queries) GetWorkspaceTasks(ctx context.Context, arg GetWorkspaceTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceTasks, arg.WorkspaceID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Assignee,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Due,
			&i.ParentTask,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceUserAssignedTasks = `-- name: GetWorkspaceUserAssignedTasks :many
SELECT id, workspace_id, assignee, created_by, name, description, due, parent_task, status, priority, created_at, updated_at FROM tasks
WHERE assignee = $1 AND workspace_id = $2
ORDER BY created_at DESC
OFFSET $3
LIMIT $4
`

type GetWorkspaceUserAssignedTasksParams struct {
	Assignee    uuid.NullUUID
	WorkspaceID uuid.UUID
	Offset      int32
	Limit       int32
}

func (q *Queries) GetWorkspaceUserAssignedTasks(ctx context.Context, arg GetWorkspaceUserAssignedTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceUserAssignedTasks,
		arg.Assignee,
		arg.WorkspaceID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Assignee,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Due,
			&i.ParentTask,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceUserCreatedTasks = `-- name: GetWorkspaceUserCreatedTasks :many
SELECT id, workspace_id, assignee, created_by, name, description, due, parent_task, status, priority, created_at, updated_at FROM tasks
WHERE created_by = $1 AND workspace_id = $2
ORDER BY created_at DESC
OFFSET $3
LIMIT $4
`

type GetWorkspaceUserCreatedTasksParams struct {
	CreatedBy   uuid.NullUUID
	WorkspaceID uuid.UUID
	Offset      int32
	Limit       int32
}

func (q *Queries) GetWorkspaceUserCreatedTasks(ctx context.Context, arg GetWorkspaceUserCreatedTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceUserCreatedTasks,
		arg.CreatedBy,
		arg.WorkspaceID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Assignee,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Due,
			&i.ParentTask,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
